version: '3.7'

services:

  client_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: client_service
    ports:
      - "5000:3000"
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./tsconfig.json:/app/tsconfig.json
    networks:
      - loomi_network
    restart: unless-stopped
    env_file:
      - .env

  postgres:
    image: postgres:15
    container_name: postgres_container_client_service
    restart: unless-stopped
    environment:
      POSTGRES_DB: client_service_db
      POSTGRES_USER: client
      POSTGRES_PASSWORD: 12345678
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - loomi_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_client_service
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: lucas@admin.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    ports:
      - "5050:80"
    networks:
      - loomi_network
    depends_on:
      - postgres

volumes:
  pgdata:

networks:
  loomi_network:
    external: true